formatter: json

sections:
  show:
    - inputs

content: |-
  ## Exampless

  ## ISmaeel Haider

  {{ .Inputs }}

output:
  file: ../../../../../docs/ltscale-cli/VPC.md

sort:
  enabled: true
  by: type

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true