AWSTemplateFormatVersion: 2010-09-09
Description: Configure AWS Config rules to check that your S3 buckets do not allow public access

Parameters:
  ConfigRuleName:
    Type: 'String'
    Description: 'Name for the Config rule'
  
  ManagedResourcePrefix:
    Type: 'String'
    Description: 'Prefix for the managed resources'

Resources:
  CheckForS3PublicWrite:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: !Sub ${ConfigRuleName}
      Description: Checks that your S3 buckets do not allow public write access. If an S3 bucket policy or bucket ACL allows public write access, the bucket is noncompliant.
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket

Outputs:
  CheckForS3PublicWriteArn:
    Description: Checks that your S3 buckets do not allow public write access. If an S3 bucket policy or bucket ACL allows public write access, the bucket is noncompliant.
    Value: !GetAtt CheckForS3PublicWrite.Arn
    Export:
      Name:
        !Sub "${ManagedResourcePrefix}-CheckForS3PublicWriteArn"