title: Litmus Scale
email: support@litmusscale.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
api_url: "https://api.demo.litmusscale.com"
admin_url: "https://admin.demo.litmusscale.com"
idp_url: "https://idp.demo.litmusscale.com"
twitter_username: jekyllrb
github_username:  jekyll
theme: just-the-docs
plugins:
  - jekyll-feed
